### ISSUE TITLE
terminate called after throwing an instance of 'RosMsgParser::RangeException'

### ISSUE THREAD

**Issue by carlin314** [facontidavide/ros_msg_parser#10]
Hi,

thanks for great work, what does under means when parsing a rosbag:

terminate called after throwing an instance of 'RosMsgParser::RangeException'
  what():  Floating point truncated

My Environment: Ubuntu 18.04 ROS Melodic

BR

**Comment by carlin314** [comment]
It seems the deserialize function has some problem. 

```cpp
const auto deserialized_msg = parsers.deserialize(topic_name, msg_instance);
```
![image](https://user-images.githubusercontent.com/16414165/130574728-5dfdbe0a-8886-4b02-b458-9db5b710b6c5.png)

![image](https://user-images.githubusercontent.com/16414165/130574592-97407e1b-b4ab-4ed6-bbed-b56d6f9fa5eb.png)

![image](https://user-images.githubusercontent.com/16414165/130574556-74d96ff1-f0a1-4241-a58c-9b2b35ec3152.png)

**Comment by lxj97** [comment]
Hi carlin314 , I met the same problem. Did you fixed it ?

**Comment by facontidavide** [comment]
a very basic search into past solved issue would reveal that this "issue" has been mentioned a number of times in the past.
The problem is that your number can not be represented precisely as a double.

What should I do?

- tell you "hey, the value can not be represented in PlotJuggler"?
- or silently CHANGE your value and then hear the complaints about that?

**Comment by lxj97** [comment]
![image](https://user-images.githubusercontent.com/92908051/145962919-f9b16b33-dd4b-4411-a162-a32249f7507f.png)

> This is not a problem but by design. Your number can not be represented as a floating point, because it would not be the "same" number.
> 
> If you are ok with that, just remove the check. If you are not OK with that, catch the exception and convert it to **uint64_t** or **int64_t**

thanks for your reply!

I understand that the cause of the exception is floating truncated as it says. I tryed catch and convert it to uint64_t or int64_t, but simply do that doesn't work, becase the DeserializedMsg requires a double value. May I ask you for some advice ?

https://user-images.githubusercontent.com/92908051/145962919-f9b16b33-dd4b-4411-a162-a32249f7507f.png
