### ISSUE TITLE
Could we package a release version？

### ISSUE THREAD

**Issue by tsukione** [facontidavide/ros_msg_parser#15]
Could we package a release version？

**Comment by tsukione** [comment]
hi, @facontidavide . May this request take a moment of your time to tag it, and give it a version number.
Thanks a lot.

**Comment by facontidavide** [comment]
releasing for melodic and noetic

**Comment by tsukione** [comment]
thanks a lot : )

**Comment by peci1** [comment]
@facontidavide The releases did not go well. Could you please have a look at it?
