### ISSUE TITLE
ROS2 Support?

### ISSUE THREAD

**Issue by nyxaria** [facontidavide/ros_msg_parser#3]
Will this package be usable for ROS2? I am currently looking into making a generic subscriber and then unpack the values into a JSON, but have no found if something like this is possible in ROS2. Any ideas?

**Comment by facontidavide** [comment]
I implemented this already in PlotJuggler, but it is not currently available as an isolated package. It will eventually

**Comment by nyxaria** [comment]
Thank you for your reply. I found your package `ros2_introspection`, but am confused as to how to obtain ` rmw_serialized_message_t* serialized_message;`. Would you be so kind as to explain this to me?

To make it scalable, I presume you need a string name of all topic's message_type (where you need to register once). Have you implemented something like this before?

Many thanks

**Comment by nyxaria** [comment]
I presume the serialized_message comes from https://github.com/ros2/rosbag2/blob/c34601acba77d08c22211d3eb062b8ba867fef71/rosbag2_transport/src/rosbag2_transport/generic_subscription.cpp?

**Comment by facontidavide** [comment]
exactly, this means that it change in all the version of ROS2 (API is continuously broken)

**Comment by nyxaria** [comment]
Thank you! I will try to take it from here, might pop back in case I'm really stuck

**Comment by facontidavide** [comment]
please use the Github issue of ros2_introspection, this repo is related to ROS1 only
